apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-aat
  labels:
    typeserv: test-aat
spec:
  selector:
    matchLabels:
      typeserv: test-aat
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        typeserv: test-aat
    spec:
      containers:
      - name: test-aat
        image: registry.tools.3stripes.net/pea-coreintegration/coreintegration/test-aat:alpine.AdidasOSOpenJre11.bwcebase2.7.2.v1_v1.0.0
        imagePullPolicy: Always
        volumeMounts:
            - mountPath: /resources/addons/certs/
              name: certs-share
              readOnly: true
        env:
              - name: BW_PROFILE
                value : K8s
              - name: CUSTOM_LOGBACK
                value : "true"
              - name: BW_APP_MONITORING_CONFIG
                value : '{"url":"http://tibcobwcemon-sit.cite-mon-sit.svc.cluster.local:80"}'
              - name: BW_JMX_CONFIG
                value : "9099"
              - name: BW_ENGINE_THREADCOUNT
                value : "8"
              - name: BW_JAVA_OPTS
                value : "-Xmx1024M -Xms256M -XX:NewSize=128m -XX:MaxNewSize=256m -Dbw.engine.opentelemetry.enable=true -Dbw.engine.opentelemetry.span.exporter=com.tibco.bw.opentelemetry.exporter.jaeger -Dbw.engine.opentelemetry.span.exporter.endpoint=http://jaeger-collector.tracing.svc.cluster.local:14250/api/traces"
              - name: MEMORY_LIMIT
                value : "1024M"
              - name: BW_JAVA_GC_OPTS
                value : "-XX:-UseGCOverheadLimit"
              - name: BW_PROMETHEUS_ENABLE
                value : "true"
              - name: AuditErrorLogger
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: AuditErrorLogger
              - name: AuditErrorLoglevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: AuditErrorLoglevel
              - name: AuditLogger
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: AuditLogger
              - name: AuditLogLevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: AuditLogLevel
              - name: auditPayloadEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: auditPayloadEnabled
              - name: BusinessObject
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: BusinessObject
              - name: ComponentType
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ComponentType
              - name: ConsoleAlertLoggingEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ConsoleAlertLoggingEnabled
              - name: ConsoleLoggingEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ConsoleLoggingEnabled
              - name: DeploymentENV
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: DeploymentENV
              - name: enableRecoverySleep
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: enableRecoverySleep
              - name: errorPayloadEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: errorPayloadEnabled
              - name: ExceptionLookupDataFormat
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ExceptionLookupDataFormat
              - name: ExceptionLookupFile
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ExceptionLookupFile
              - name: FrameworkErrorLogger
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FrameworkErrorLogger
              - name: FrameworkErrorLogLevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FrameworkErrorLogLevel
              - name: FrameworkLogger
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FrameworkLogger
              - name: FrameworkLogLevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FrameworkLogLevel
              - name: FWErrorHTTPClient
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWErrorHTTPClient
              - name: FWErrorServiceHostName
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWErrorServiceHostName
              - name: FWErrorServicePort
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWErrorServicePort
              - name: FWErrorServiceResourcePath
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWErrorServiceResourcePath
              - name: FWLogHTTPClient
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWLogHTTPClient
              - name: FWLogServiceHostName
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWLogServiceHostName
              - name: FWLogServicePort
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWLogServicePort
              - name: FWLogServiceResourcePath
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: FWLogServiceResourcePath
              - name: InterfaceID
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: InterfaceID
              - name: InterfaceSourceProtocol
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: InterfaceSourceProtocol
              - name: InterfaceTargetProtocol
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: InterfaceTargetProtocol
              - name: JMSMaxSessions
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: JMSMaxSessions
              - name: KafkaKeyPassword
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaKeyPassword
              - name: KafkaKeyStoreLocation
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaKeyStoreLocation
              - name: KafkaKeyStorePassword
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaKeyStorePassword
              - name: KafkaMaxReqSize
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaMaxReqSize
              - name: KafkaMsgKey
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaMsgKey
              - name: KafkaRetry
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaRetry
              - name: KafkaTrustStoreLocation
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaTrustStoreLocation
              - name: KafkaTrustStorePassword
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KafkaTrustStorePassword
              - name: KibanaENV
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KibanaENV
              - name: KibanaErrorLoglevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KibanaErrorLoglevel
              - name: KibanaLoglevel
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KibanaLoglevel
              - name: KibanaVersion
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: KibanaVersion
              - name: Leanixid
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: Leanixid
              - name: ObjectEMSPassword
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSPassword
              - name: ObjectEMSQueueConnectionFactory
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSQueueConnectionFactory
              - name: ObjectEMSQueueTopicPub
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSQueueTopicPub
              - name: ObjectEMSQueueTopicSub
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSQueueTopicSub
              - name: ObjectEMSTopicConnectionFactory
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSTopicConnectionFactory
              - name: ObjectEMSUrl
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSUrl
              - name: ObjectEMSUsername
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectEMSUsername
              - name: ObjectKafkaBootStrapServer
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectKafkaBootStrapServer
              - name: ObjectKafkaConnectionTimeout
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectKafkaConnectionTimeout
              - name: ObjectKafkaPassword
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectKafkaPassword
              - name: ObjectKafkaTopic
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectKafkaTopic
              - name: ObjectKafkaUsername
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ObjectKafkaUsername
              - name: RecoverySleepTime
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: RecoverySleepTime
              - name: RepoName
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: RepoName
              - name: ScenarioID
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: ScenarioID
              - name: SourceSystem
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: SourceSystem
              - name: TargetSystem
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: TargetSystem
              - name: WebserviceAlertLoggingEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: WebserviceAlertLoggingEnabled
              - name: WebserviceLoggingEnabled
                valueFrom:
                  configMapKeyRef:
                    name: test-aat-configmap-sit
                    key: WebserviceLoggingEnabled
        resources:
             requests:
                 memory: "1024Mi"
                 cpu: "500m"
             limits:
                 memory: "1536Mi"
                 cpu: "1"
      imagePullSecrets:
        - name: registry-tools-3stripes-net-cred
      volumes:
        - name: certs-share
          projected:
            sources:
              - secret:
                   name: test-aat-secret-sit
